plot(PigeonEWLData$`Air Temp (°C)`, PigeonEWLData$`Water evap. (g/hr)`, xlab = "Air Temp (ºC)", ylab = "EWL (g/hr)",main = "Evaporative Water Loss vs Air Temperature", xlim = c(30,60), ylim = c(0,10))
abline(lm(PigeonEWLData$`Water evap. (g/hr)` ~ PigeonEWLData$`Air Temp (°C)` ), col = "blue")
abline(h=8.04, col="blue")
EWLAcoeff<-lm(PigeonEWLData$`Water evap. (g/hr)` ~ PigeonEWLData$`Air Temp (°C)` )
EWLLineData<-data.frame()
EWLLineData<-rbind(EWLLineData, data.frame(Intercept = EWLcoeff$coefficients[1], Slope = EWLcoeff$coefficients[2]))
write.table(EWLLineData, file = "~/EWLFile")

plot(PigeonEWLData$`Body temp. (°C)`, PigeonEWLData$`Water evap. (g/hr)`, xlab = "Body Temp (ºC)", ylab = "EWL (g/hr)",main = "Evaporative Water Loss vs Body Temperature", xlim = c(35,50), ylim = c(0,10))
abline(lm(PigeonEWLData$`Water evap. (g/hr)` ~ PigeonEWLData$`Body temp. (°C)` ), col = "blue")
abline(h=8.04, col="blue")
EWLBcoeff<-lm(PigeonEWLData$`Water evap. (g/hr)` ~ PigeonEWLData$`Body temp. (°C)` )
EWLLineData<-data.frame()
EWLLineData<-rbind(EWLLineData, data.frame(Intercept = EWLcoeff$coefficients[1], Slope = EWLcoeff$coefficients[2]))
write.table(EWLLineData, file = "~/EWLFile")

plot(PigeonEWLData$`Air Temp (°C)` , PigeonEWLData$`Body temp. (°C)`, xlab = "Air Temp (ºC)", ylab = "Body Temp (ºC)",main = "Air Temperature vs Body Temperature", xlim = c(30,60), ylim = c(30,60))
abline(lm(PigeonEWLData$`Body temp. (°C)` ~ PigeonEWLData$`Air Temp (°C)` ), col = "blue")
EWLcoeff<-lm(PigeonEWLData$`Body temp. (°C)` ~ PigeonEWLData$`Air Temp (°C)` )
EWLLineData<-data.frame()
EWLLineData<-rbind(EWLLineData, data.frame(Intercept = EWLcoeff$coefficients[1], Slope = EWLcoeff$coefficients[2]))
write.table(EWLLineData, file = "~/EWLFile")